/// Title 0
// god i wish byond had a good way to end sounds early
/datum/looping_sound/spaceman_music
	start_sound = 'local/code/modules/slashco13/sound/slasher/spaceman/title0/01Title0.ogg'
	start_length = 3 SECONDS
	mid_sounds = list(
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/02Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/03Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/04Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/05Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/06Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/07Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/08Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/09Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/10Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/11Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/12Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/13Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/14Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/15Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/16Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/17Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/18Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/19Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/20Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/21Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/22Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/23Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/24Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/25Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/26Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/27Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/28Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/29Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/30Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/31Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/32Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/33Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/34Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/35Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/36Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/37Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/38Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/39Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/40Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/41Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/42Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/43Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/44Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/45Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/46Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/47Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/48Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/49Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/50Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/51Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/52Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/53Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/54Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/55Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/56Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/57Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/58Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/59Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/60Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/61Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/62Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/63Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/64Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/65Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/66Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/67Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/68Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/69Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/70Title0.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title0/71Title0.ogg' = 1, \
	)
	mid_length = 3 SECONDS
	end_sound = null
	each_once = TRUE
	in_order = TRUE
	var/total_length = 3 MINUTES + 33 SECONDS

/// Title Two
/datum/looping_sound/spaceman_music/title_two
	start_sound = 'local/code/modules/slashco13/sound/slasher/spaceman/title2/01Title2.ogg'
	start_length = 2 SECONDS
	mid_sounds = list(
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/02Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/03Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/04Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/05Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/06Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/07Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/08Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/09Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/10Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/11Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/12Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/13Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/14Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/15Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/16Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/17Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/18Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/19Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/20Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/21Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/22Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/23Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/24Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/25Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/26Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/27Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/28Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/29Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/30Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/31Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/32Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/33Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/34Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/35Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/36Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/37Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/38Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/39Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/40Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/41Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/42Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/43Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/44Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/45Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/46Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/47Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/48Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/49Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/50Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/51Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/52Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/53Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/54Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/55Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/56Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/57Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/58Title2.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title2/59Title2.ogg' = 1, \
	)
	mid_length = 2 SECONDS
	end_sound = null
	total_length = 1 MINUTES + 58 SECONDS

/// Title 3
/datum/looping_sound/spaceman_music/title_three
	start_sound = 'local/code/modules/slashco13/sound/slasher/spaceman/title3/01Title3.ogg'
	start_length = 8 SECONDS
	mid_sounds = list(
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/02Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/03Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/04Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/05Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/06Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/07Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/08Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/09Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/10Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/11Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/12Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/13Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/14Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/15Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/16Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/17Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/18Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/19Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/20Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/21Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/22Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/23Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/24Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/25Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/26Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/27Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/28Title3.ogg' = 1, \
		'local/code/modules/slashco13/sound/slasher/spaceman/title3/29Title3.ogg' = 1, \
	)
	mid_length = 3 MINUTES + 52 SECONDS
	end_sound = null
