/datum/asset/simple/namespaced/effigy_ui
	assets = list(
		"ChakraPetch-Medium.ttf" = 'local/interface/fonts/ChakraPetch-Medium.ttf',
		"ChakraPetch-MediumItalic.ttf" = 'local/interface/fonts/ChakraPetch-MediumItalic.ttf',
		"ChakraPetch-SemiBold.ttf" = 'local/interface/fonts/ChakraPetch-SemiBold.ttf',
		"ChakraPetch-SemiBoldItalic.ttf" = 'local/interface/fonts/ChakraPetch-SemiBoldItalic.ttf',
		"ChakraPetch-Bold.ttf" = 'local/interface/fonts/ChakraPetch-Bold.ttf',
		"ChakraPetch-BoldItalic.ttf" = 'local/interface/fonts/ChakraPetch-BoldItalic.ttf',
		"IBMPlexSans-Medium.ttf" = 'local/interface/fonts/IBMPlexSans-Medium.ttf',
		"IBMPlexSans-MediumItalic.ttf" = 'local/interface/fonts/IBMPlexSans-MediumItalic.ttf',
		"IBMPlexSans-SemiBold.ttf" = 'local/interface/fonts/IBMPlexSans-SemiBold.ttf',
		"IBMPlexSans-SemiBoldItalic.ttf" = 'local/interface/fonts/IBMPlexSans-SemiBoldItalic.ttf',
		"IBMPlexSans-Bold.ttf" = 'local/interface/fonts/IBMPlexSans-Bold.ttf',
		"IBMPlexSans-BoldItalic.ttf" = 'local/interface/fonts/IBMPlexSans-BoldItalic.ttf',
		"TitilliumWeb-Regular.ttf" = 'local/interface/fonts/TitilliumWeb-Regular.ttf',
		"TitilliumWeb-Italic.ttf" = 'local/interface/fonts/TitilliumWeb-Italic.ttf',
		"TitilliumWeb-SemiBold.ttf" = 'local/interface/fonts/TitilliumWeb-SemiBold.ttf',
		"TitilliumWeb-SemiBoldItalic.ttf" = 'local/interface/fonts/TitilliumWeb-SemiBoldItalic.ttf',
		"TitilliumWeb-Bold.ttf" = 'local/interface/fonts/TitilliumWeb-Bold.ttf',
		"TitilliumWeb-BoldItalic.ttf" = 'local/interface/fonts/TitilliumWeb-BoldItalic.ttf',
		"UbuntuMono-Regular.ttf" = 'local/interface/fonts/UbuntuMono-Regular.ttf',
		"UbuntuMono-Italic.ttf" = 'local/interface/fonts/UbuntuMono-Italic.ttf',
		"UbuntuMono-Bold.ttf" = 'local/interface/fonts/UbuntuMono-Bold.ttf',
		"UbuntuMono-BoldItalic.ttf" = 'local/interface/fonts/UbuntuMono-BoldItalic.ttf',
	)

var/list/extra_resources = list(\
	'local/interface/fonts/ChakraPetch-Medium.ttf',
	'local/interface/fonts/ChakraPetch-MediumItalic.ttf',
	'local/interface/fonts/ChakraPetch-SemiBold.ttf',
	'local/interface/fonts/ChakraPetch-SemiBoldItalic.ttf',
	'local/interface/fonts/ChakraPetch-Bold.ttf',
	'local/interface/fonts/ChakraPetch-BoldItalic.ttf',
	'local/interface/fonts/IBMPlexSans-Medium.ttf',
	'local/interface/fonts/IBMPlexSans-MediumItalic.ttf',
	'local/interface/fonts/IBMPlexSans-SemiBold.ttf',
	'local/interface/fonts/IBMPlexSans-SemiBoldItalic.ttf',
	'local/interface/fonts/IBMPlexSans-Bold.ttf',
	'local/interface/fonts/IBMPlexSans-BoldItalic.ttf',
	'local/interface/fonts/TitilliumWeb-Regular.ttf',
	'local/interface/fonts/TitilliumWeb-Italic.ttf',
	'local/interface/fonts/TitilliumWeb-SemiBoldItalic.ttf',
	'local/interface/fonts/TitilliumWeb-Bold.ttf',
	'local/interface/fonts/TitilliumWeb-BoldItalic.ttf',
	'local/interface/fonts/UbuntuMono-Regular.ttf',
	'local/interface/fonts/UbuntuMono-Italic.ttf',
	'local/interface/fonts/UbuntuMono-Bold.ttf',
	'local/interface/fonts/UbuntuMono-BoldItalic.ttf'
)
